Orders
TopTrip-ge/top-trip-cloud-functions pull request #11
Opened 2022-11-08 10:59 UTC by davin01001

operations with orders

2022-11-08 16:49 UTC, pavelsokolov21 requested changes

2022-11-08 16:49 UTC, pavelsokolov21 commented on functions/src/api/orders/controllers/orders/create-order.ts
> +// import * as admin from "firebase-admin";
!

2022-11-08 16:49 UTC, pavelsokolov21 commented on functions/src/api/orders/controllers/orders/get-all-orders.ts
> +    //   .filter( (order) => (order.status != ORDER_STATUSES.DECLINED
!

2022-11-08 16:49 UTC, pavelsokolov21 commented on functions/src/api/orders/controllers/orders/get-order-by-id.ts
> +// import * as admin from "firebase-admin";
!

2022-11-08 16:49 UTC, pavelsokolov21 commented on functions/src/api/orders/controllers/orders/get-order-by-id.ts
> +    // const user = await admin.auth().getUser(uid);
!

2022-11-08 16:49 UTC, pavelsokolov21 commented on functions/src/api/orders/controllers/orders/update-order.ts
> +// import * as admin from "firebase-admin";
!

2022-11-08 16:49 UTC, pavelsokolov21 commented on functions/src/api/orders/controllers/orders/update-order.ts
> +    // const authInstance = admin.auth();
!

2022-11-08 16:49 UTC, pavelsokolov21 commented on functions/src/api/orders/controllers/orders/update-order.ts
> +      // date,
!

2022-11-08 16:49 UTC, pavelsokolov21 commented
Удалить .idea

2022-11-09 06:31 UTC, davin01001 commented
agree with all, changed

2022-11-09 06:55 UTC, pavelsokolov21 approved these changes

2022-11-09 06:56 UTC, merged